sudo: false

language: node_js

node_js:
  - "4"
  - "6"
  - "7"

install:
  # Install dependencies and build
  - npm install

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - npm test
